name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 34.125.182.254
          username: shashanketa
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            cd ~/app
            pkill node
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            git pull
            npm install
            nohup npm run start > /dev/null 2>&1 &
          
