name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into VM
        uses: appleboy/ssh-action@master
        with:
          host: 34.125.182.254
          username: shashanketa
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami

      - name: Add Public keys
        run: |
          whoami
          ls -lah
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh
          chmod 600 ~/.ssh/id_rsa.pub
          ssh shashanketa@34.125.182.254 'pkill node'

      - name: Stop main process
        run: |
          # Execute command to stop the main process
          ssh shashanketa@34.125.182.254 'pkill node'

      - name: Deploy
        run: |
          # Execute deployment commands on the VM using SSH
          ssh shashanketa@34.125.182.254  'cd ~/app && git pull && npm install'

      - name: Start
        run: |
          # Execute deployment commands on the VM using SSH
          ssh shashanketa@34.125.182.254  'cd ~/app && nohup npm run start > /dev/null 2>&1 &'
          
